### ISSUE TITLE
Game Design/MVP Requirements

### ISSUE THREAD

**Issue by Semviel** [koomb/turn-based-strategy#1]
### Problem
Before developing we should design what features we are going to include in our first 0.1 release.

### Solution
For that, we are going to discuss it and write new ideas in the header message.

## Пошаговая стратегия

Данная видеоигра вдохновлена игрой на бумаге, в которую я играл с отцом в детстве, поэтому сначала изложу суть оригинальной игры (которая на сколько я понимаю, является идеей отца, т.к. я пока ни от кого не слышал, чтобы кто-то еще в нее когда-то играл)

### Правила оригинальной игры

2 игрока имеют некоторый набор войск - автоматчики, пулеметчики, гранатометчики, различные танки, пусковые установки, артиллерия и т.д. Все эти войска имеют некоторый способ рисования - автоматчик - круг и три палки выходящие из него (палки показывают в каком направлении он будет стрелять), пулеметчик - круг и 6 палок, танки обычно являлись большими прямоугольниками с кругом внутри (схематично обозначает башню) и парой палок из "башни".

Брался лист бумаги и сначал один игрок, потом другой на своей половине листа (лист сгибался и игроки не видели, как расположены юниты противника) рисовал юнитов и куда они будут стрелять (палки). Затем лист вскрывался (игроки кладут его перед собой и смотрят на картину целиком) и по очереди выбирают какой юнит будет стрелять. Выбранный юнит стреляет по договоренности - либо какой-то одной палкой, либо всеми (обычно пехота стреляет всеми, техника по одной). Выстрел производился наложением линейки на небольшую палку, что приводило к тому, что ты должен самостоятельно "на глаз" оценить - попадет юнит или нет (+ не все могли убить всех, например пехота не могла нанести урон танку) 

Какое-то время назад у меня появилась идея перенести механику стратегического покера на электронные рельсы.

Стоит также отметить, что у игры существовала глобальная карта, на которой мы перемещали армии, покупали юниты за заработанные в боях деньги (деньги давались за убийство противников) - существовала простая военная экономическая модель.

### Идея для видеоигры

Видеоигру предлагается сделать комплекснее, но есть некоторые концепции, которые должны перекочевать из оригинальной игры:

1. _Хардкорность_ - юнитны не живут долго, это люди, которые погибают с одного выстрело и довольно бодро разрываются от взрывов
2. _Покерность_ - по сути оригинальная игра похожа на покер - сначала делается ставка вслепую (ты выставляешь войска из имеющихся, ты берешь их столько сколько ты хочешь, расставляешь так, как хочешь и направления выстрелов выбираешь сам, ориентируясь только на удачу) - блайнд, а потом, когда все вскрыто, начинается выбор "на глаз", где ты решаешь, рисковать или нет, смотришь, кого может убить противник и решаешь кого нужно убрать сейчас (если ты конечно можешь это сделать)

Второй пункт подразумевает именно некоторую случайность, механику overthinking'а противника, где ты должен предугадать его поведение и не дать ему предугадать твое.

Для этого предлагается сделать игру смешением стратегии в реальном времени и пошаговой стратегии. Игра должна быть рассчитана на онлайн бои по 20-60 минут на небольших картах (время зависит от кол-ва игроков) с некоторым набором войск + должна быть одиночная компания и тренировочные offline бои.

К тому же я хочу отказать от реалистичности происходящего, плоскости карты (стратегия в 3D) - можно взять некоторый выдуманный футуристичный сеттинг (возможно даже не человеческий мир, а какую-нибудь иную планету, с уникальной флорой, фауной и terrain'ом.

Ключевая механика игры заключается в следующем:
1. Игроки расставляют войска и отдают им команды
1. Игровой цикл состоит из двух сменяющихся частей - этапа командования и этапа наблюдения
1. Этап командования происходит в остановившемся времени (ничто не двигается)
1. Этап наблюдения происходит в идущем времени (юниты выполняют отданные приказы - идут куда приказано, стреляют куда приказано)
1. Юниты обладают своими уникальными наборами способностей, например штурмовик может стрелять на бегу, а снайпер не может, зато для снайпера можно выбрать конкретную точку выстрела или target-юнита, которого он убьет как только прицелится (если конечно самого снайпера не убьют) и т.д. (это был пример)
1. Приказы стоят некоторых очков (т.е. юнит обладает некоторым умением, которое стоит некоторое кол-во очков)
1. Умения имеют время перезарядки или кол-во использований до перезарядки умения
1. Удачные действия - убийство, взрыв чего-нибудь и т.д. должны поощряться дополнительными очками действий
1. Очки действия восстанавливаются во время этапа наблюдения с каждой секундой
1. У игроков есть окно в которое они могут приостановить игру для этапа командования - приостановил один - игра приостановилась у всех. В зависимости от того, сколько времени прошло игрокам будет дано различное время на выдачу команд - думать надо быстро, по истечению которого начнется этап наблюдения
1. Наблюдение в среднем должно длится 3-7 секунд, игрок должен уметь пересматривать происходящее (если карта достаточно большая или приходится вести одновременно 2+ боя)
1. Так же сделать глобальную карту - для мультиплеера на ней можно выбирать локацию для боя и искать по параметрам противника(-ов), в одиночной компании путешествовать по миру со своим отрядом, выполняя квесты (сюжетные и не очень)

**Comment by Semviel** [comment]
> **Как работает убийство "на глаз" в видеоигре на этапе командования?**

Разные юниты могут стрелять по-разному - игрок может выбрать тот или иной тип огня для юнита, например условному штурмовику можно дать спосбность вести огонь на бегу. Для этого игрок обозначает точку в которую бежит штурмовик и область, по которой он ведет огонь. Огонь ведется менее точно, зато юнит двигается.

> **Каковы условия победы и проигрыша?**

Пока все юниты не погибнут или кто-то не сдастся. Для более сложных режимов игры можно делать более сложные условия (защитить некоторый объект, переместить все воиска в указанную локацию и т.д.)

> **сколько игроков может одновременно участвовать в бою?**

2-4 я думаю

> **Как тогда будет выглядеть игровая карта(делиться на n равных частей, наверно)?**

Пока не знаю, будет просто 4 "случайные" зоны для спавна юнитов в начале игры (начальных лагеря)

> **Не будет ли излишним усложнением возможность вести 2+ боя одновременно?**

Возможно, в любом случае нужно тестить. К тому же 2 параллельные стычки могут произойти и у 2-х игроков

> **Как рассчитывается время этапа наблюдения?**

Грубо: чем дольше идет активная фаза, тем больше времени дается на командование и тем больше имеется очков. Расчет конкретных цифр - балансировочная задача (учим/вспоминаем диффуры 😈)

> **Как часто можно включать этап командования?**

Должно пройти по крайней мере _n_ секунд (миллисекунд) - считаем на этапе балансировки, думаю зависимость от множества параметров - кол-ва юнитов, размера карты, времени на активную фазу и т.д.

> **Допустим, игрок дал приказ юниту, он не успел выполнить его до конца этапа наблюдения. Что происходит с этим приказом? Можно ли его отменить? Возвращаются ли очки действия?**

* приказ не отменяется и выполняется пока не будет закончен
* если игрок дал новый приказ, то приказ отменяется, очки приказов не восстанавливаются

> **Игроки расставляют юнитов до начала боя?**

Да, на специальную "данную" для spawn'а игроку зону

> **Могут ли они ставить новых юнитов в процессе боя?**

Да, рядом с союзниками (возможно) или в начальную spawn зону

> **Убирать старых?**

Возможно можно будет эвакуировать юнитов, при желании (как способ получить "ничью")

> **Менять их положение на карте?**

Подразумевается, что юниты двигаются, прячутся за укрытиями и т.д.

**Comment by hypnospinner** [comment]
Attention ⚠️ 

This issue should be converted to the list of game mechanic issues and closed as a duplicate

**Comment by hypnospinner** [comment]
MVP was privately build up => issue is closed
